#!/usr/bin/env bash
# scripts/dev-local.sh — One-shot local dev environment.
#
# Boots a productive nostrdome-relay on :7777 with persistent SQLite,
# seeds a community on first run (and stores the owner nsec for reuse),
# then starts `vite` against it. No code edits needed: env vars + the
# defaults in src/config.tsx do the wiring.
#
# Re-running reuses the existing community + nsec. Pass `--reset` to
# wipe the local data dir and start fresh.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATA_DIR="${ROOT}/.dev-data"
RELAY_DB="${DATA_DIR}/relay-db"
NSEC_FILE="${DATA_DIR}/owner.nsec"
RELAY_TOML="${DATA_DIR}/relay.toml"
RELAY_BIN="${ROOT}/relay/nostrdome-relay"
RELAY_PORT="${RELAY_PORT:-7777}"
GROUP_ID="${GROUP_ID:-mi-comunidad}"
GROUP_NAME="${GROUP_NAME:-Mi Comunidad Local}"

# ── flags ─────────────────────────────────────────────────────────────
for arg in "$@"; do
  case "$arg" in
    --reset)
      echo "→ Wiping ${DATA_DIR}…"
      rm -rf "$DATA_DIR"
      ;;
    --help|-h)
      sed -n '2,12p' "$0" | sed 's|^# \{0,1\}||'
      exit 0
      ;;
  esac
done

mkdir -p "$DATA_DIR"

# ── 1. build relay binary if missing or stale ────────────────────────
if [ ! -x "$RELAY_BIN" ] || \
   [ "${ROOT}/relay/cmd/nostrdome-relay/main.go" -nt "$RELAY_BIN" ] || \
   [ "${ROOT}/relay/internal/groupstate/state.go" -nt "$RELAY_BIN" ]; then
  echo "→ Building nostrdome-relay…"
  (cd "${ROOT}/relay" && go build -o nostrdome-relay ./cmd/nostrdome-relay)
fi

# ── 2. write a dev-only relay.toml pointed at .dev-data ───────────────
cat > "$RELAY_TOML" <<EOF
# Auto-generated by scripts/dev-local.sh. Do not commit.
[relay]
addr = ":${RELAY_PORT}"
name = "nostrdome-dev"
description = "Local dev relay seeded by scripts/dev-local.sh"
version = "0.1.0-dev"

[storage]
path = "${RELAY_DB}"

[ratelimit]
per_minute = 1000
per_hour = 60000
burst_size = 100

[logging]
level = "info"
format = "text"
EOF

# ── 3. start the relay in background; ensure cleanup on exit ──────────
echo "→ Starting relay on ws://localhost:${RELAY_PORT} (db: ${RELAY_DB})"
"$RELAY_BIN" -config "$RELAY_TOML" &
RELAY_PID=$!

cleanup() {
  if kill -0 "$RELAY_PID" 2>/dev/null; then
    echo ""
    echo "→ Stopping relay (pid ${RELAY_PID})…"
    kill "$RELAY_PID" 2>/dev/null || true
    wait "$RELAY_PID" 2>/dev/null || true
  fi
}
trap cleanup INT TERM EXIT

# ── 4. wait until /  responds (NIP-11 doc → relay is up) ──────────────
echo -n "→ Waiting for relay to be ready"
for _ in $(seq 1 50); do
  if curl -sf -H "Accept: application/nostr+json" \
       "http://localhost:${RELAY_PORT}/" > /dev/null 2>&1; then
    echo " ✓"
    break
  fi
  echo -n "."
  sleep 0.2
done

# ── 5. seed only if the db has no community yet ───────────────────────
# Cheap heuristic: presence of the nsec file means we already seeded.
SEED_LOG="${DATA_DIR}/seed.log"
if [ ! -f "$NSEC_FILE" ]; then
  echo "→ Seeding fresh community '${GROUP_ID}'…"
  # Stream seed output to BOTH the terminal and a log file so failures
  # are visible immediately and we can still grep the nsec out. Disable
  # set -e for the pipeline so we can capture the exit code ourselves
  # (PIPESTATUS only works if the shell didn't already abort).
  set +e
  (cd "${ROOT}/relay" && go run ./cmd/nostrdome-seed \
    -relay "ws://localhost:${RELAY_PORT}" \
    -group "${GROUP_ID}" \
    -name "${GROUP_NAME}" \
    -about "Local dev community seeded by scripts/dev-local.sh") 2>&1 | tee "$SEED_LOG"
  SEED_RC=${PIPESTATUS[0]}
  set -e
  if [ "$SEED_RC" -ne 0 ]; then
    echo ""
    echo "✗ Seed failed (exit ${SEED_RC}). See output above; full log in ${SEED_LOG}."
    exit 1
  fi
  NSEC=$(grep -oE 'nsec1[a-z0-9]+' "$SEED_LOG" | head -1 || true)
  NPUB=$(grep -oE 'npub1[a-z0-9]+' "$SEED_LOG" | head -1 || true)
  if [ -z "$NSEC" ]; then
    echo "✗ Seed completed but did not emit an nsec. See ${SEED_LOG}."
    exit 1
  fi
  printf '%s\n' "$NSEC" > "$NSEC_FILE"
  chmod 600 "$NSEC_FILE"
  echo ""
  echo "════════════════════════════════════════════════════════════════"
  echo "  Owner nsec: $NSEC"
  echo "  Owner npub: $NPUB"
  echo "  Saved to:   ${NSEC_FILE}"
  echo "════════════════════════════════════════════════════════════════"
else
  echo "→ Reusing existing community + owner from ${NSEC_FILE}"
  echo "  $(cat "$NSEC_FILE")"
fi

# ── 6. start vite with env pointing at our relay ──────────────────────
echo ""
echo "→ Starting vite — open the URL it prints, paste the nsec above to log in."
echo "   (Ctrl+C aquí para detener relay + dev server.)"
echo ""
cd "$ROOT"
VITE_LIVE_RELAY_URL="ws://localhost:${RELAY_PORT}" \
VITE_LIVE_GROUP_ID="${GROUP_ID}" \
VITE_PUBLIC_RELAYS="" \
npm run dev
